name: Releasability status

on:
  workflow_dispatch:

jobs:
  slack-job:
    name: Test Slack
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write      # required by SonarSource/vault-action-wrapper
      contents: read       # required by checkout
    steps:
      - name: Send Slack
        uses: SonarSource/release-github-actions/slack-message@tt/slack
        with:
          channel: 'tomasz-tylenda-test'
          message-markdown: |
            # Hello World!
            This is a test message from GitHub Actions.
              - one
              - two
              - three